#!/usr/bin/bash
#PBS -l walltime=4:00:00
#PBS -A lp_vsc32982
#PBS -l nodes=1:ppn=36

cd /scratch/leuven/329/vsc32982/SCENIC2/
export PATH="${VSC_DATA}/miniconda3/bin:${PATH}"
source activate science


python template_SCENIC_part2.py
Rscript template_SCENIC_part3.R

